openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
- url: "http://localhost:3000"
  description: "ローカル環境"
- url: "https://server.test/api/v1"
  description: "本番環境"
paths:
  /login:
    post:
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /signup:
    post:
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /logout:
    post:
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  
  
