services:
  swagger_ui:
    image: swaggerapi/swagger-ui:v5.0.0
    container_name: swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ../openapi/openapi.yml:/usr/share/nginx/html/openapi.yml:ro
    environment:
      - API_URL=/openapi.yml
